### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

### ISSUE THREAD

**Issue by FujaTyping** [zentred/roblox-ugc-limiteds-spam-buyer#5]
Traceback (most recent call last):
  File "C:\Users\games\OneDrive\Desktop\UGC Limited Buyer\Zentred.py", line 3, in <module>
    with open('config.json') as config:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

**Comment by FujaTyping** [comment]
Ok i fix it
But i have more Issues

{'expectedSellerId': 190011017, 'owned': False, 'isPurchasable': True, 'id': 321570512, 'itemType': 'Asset', 'assetType': 8, 'name': 'Chill Cap', 'description': "What's cooler than being cool? Chilled.", 'productId': 29959337, 'genres': ['All'], 'itemStatus': [], 'itemRestrictions': ['Limited'], 'creatorHasVerifiedBadge': True, 'creatorType': 'User', 'creatorTargetId': 1, 'creatorName': 'Roblox', 'price': 15, 'lowestPrice': 770, 'favoriteCount': 138684, 'offSaleDeadline': None, 'saleLocationType': 'NotApplicable', 'hasResellers': True}
Traceback (most recent call last):
  File "C:\Users\games\OneDrive\Desktop\UGC Limited Buyer\Zentred.py", line 62, in <module>
    a.purchase_item()
  File "C:\Users\games\OneDrive\Desktop\UGC Limited Buyer\Zentred.py", line 36, in purchase_item
    f'https://apis.roblox.com/marketplace-sales/v1/item/{self.collectible_id}/purchase-item',
                                                         ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Bot' object has no attribute 'collectible_id'
